### ISSUE TITLE
java.lang.SecurityException: does not have permission to uri

### ISSUE THREAD

**Issue by lonelyenvoy** [lonelyenvoy/EasyCamera#3]
When ```openCamera()``` is called:
```
02-27 16:40:06.787 19558-19558/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.SecurityException: Uid 10413 does not have permission to uri 0 @ content://ink.envoy.easycamera.fileprovider/my_images/DCIM/APP_NAME/JPEG_20180227_164006_194395933.jpg
                                                       at android.os.Parcel.readException(Parcel.java:1684)
                                                       at android.os.Parcel.readException(Parcel.java:1637)
                                                       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3151)
                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1520)
                                                       at android.app.Activity.startActivityForResult(Activity.java:4399)
                                                       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:54)
                                                       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
                                                       at android.app.Activity.startActivityForResult(Activity.java:4357)
                                                       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:708)
                                                       at ink.envoy.easycamera.EasyCameraActivity.dispatchTakePictureIntent(EasyCameraActivity.java:145)
                                                       at ink.envoy.easycamera.EasyCameraActivity.openCamera(EasyCameraActivity.java:78)
                                                       at ink.envoy.easycamera.EasyCameraActivity.openCamera(EasyCameraActivity.java:50)
                                                       at APP_PACKAGE.MainActivity.access$400(MainActivity.java:44)
                                                       at APP_PACKAGE.MainActivity$4.onClick(MainActivity.java:183)
                                                       at android.view.View.performClick(View.java:5647)
                                                       at android.view.View$PerformClick.run(View.java:22462)
                                                       at android.os.Handler.handleCallback(Handler.java:754)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:163)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6276)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)
```

**Comment by lonelyenvoy** [comment]
Fixed.

*Reference*
https://stackoverflow.com/questions/24467696/android-file-provider-permission-denial
